{% set name = "xwidgets" %}
{% set version = "0.12.2" %}
{% set sha256 = "64a150a3ea24fa0fe15f368c47692be75f082f1fdc23e7c7fc58d5679af7c4a8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xwidgets/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py<35]
  features:
    - vc14    # [win]

requirements:
  build:
    - toolchain
    - cmake
    - gcc-7             # [linux]
    - xeus >=0.13.0,<0.14
    - cppzmq 4.2.3
    - xtl >=0.4.8,<0.5
    - xproperty >=0.7,<0.8
    - clangdev          # [osx]
    - libcxx            # [osx]
    - nlohmann_json >=3.1.1,<4.0
  run:
    - xeus >=0.13.0,<0.14
    - cppzmq 4.2.3
    - xtl >=0.4.8,<0.5
    - xproperty >=0.7,<0.8
    - nlohmann_json >=3.1.1,<4.0

test:
  commands:
    - test -d ${PREFIX}/include/xwidgets  # [unix]
    - test -f ${PREFIX}/include/xwidgets/xtransport.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwidgets\xtransport.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xwidgets
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ implementation of the Jupyter Interactive widgets'
  doc_url: http://xwidgets.readthedocs.io
  dev_url: https://github.com/QuantStack/xwidgets

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
