{% set name = "xwidgets" %}
{% set version = "0.13.1" %}
{% set sha256 = "d162d1e1b01c6e8b53e7eda0204367a00b21ee1bf3ba5d0c3bc9c472319aeb67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xwidgets/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py<35]
  features:
    - vc14    # [win]

requirements:
  build:
    - toolchain
    - cmake
    - gcc-7                # [linux]
    - xeus >=0.14.1,<0.15
    - cppzmq 4.3.0
    - xtl >=0.4.8,<0.5
    - xproperty >=0.7,<0.8
    - clangdev             # [osx]
    - libcxx               # [osx]
    - nlohmann_json >=3.1.2,<4.0
  run:
    - xeus >=0.14.1,<0.15
    - cppzmq 4.3.0
    - xtl >=0.4.8,<0.5
    - xproperty >=0.7,<0.8
    - nlohmann_json >=3.1.2,<4.0

test:
  commands:
    - test -d ${PREFIX}/include/xwidgets  # [unix]
    - test -f ${PREFIX}/include/xwidgets/xtransport.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwidgets\xtransport.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xwidgets
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ implementation of the Jupyter Interactive widgets'
  doc_url: http://xwidgets.readthedocs.io
  dev_url: https://github.com/QuantStack/xwidgets

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
